# Generated by Django 5.1.3 on 2024-11-20 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_remove_choice_choice_remove_question_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 2, 31, 33, 390298, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
